### ISSUE TITLE
Support Isle of Man and Monaco VAT numbers

### ISSUE THREAD

**Issue by kdeldycke** [wbond/vat_moss-python#1]
Isle of Man (country code: `IM`) share its VAT registry with the UK. Same thing for Monaco (country code: `MC`), which is sharing its registry with France.

For instance, a VAT number from a Monaco company will be reported as from France:
```python
>>> vat_moss.id.validate(u'FR12000045202')
(u'FR', u'FR12000045202', 'SAM ROBERTSHAW')
```

Same for a company based in Isle of Man:
```python
>>> vat_moss.id.validate(u'GB 000 8920 15')
(u'GB', u'GB000892015', 'DIXCART MANAGEMENT (IOM) LIMITED')
```

I still don't know in what way you can handle these exceptions with the current implementation of the `vat_moss.id.validate()` method.

**Comment by wbond** [comment]
I am looking to see if there is a way to get this info from the validation service.

That said, `IM` and `GB` charge the same VAT rate, and so do `FR` and `MC`.

Either way, this library is for calculating VAT rates on digital services, and if an ID passes validation, you are supposed to use the reverse charge mechanism, so you shouldn't actually charge VAT at all. You should just use the response from this to confirm that you can not charge VAT since the ID provided is for a registered VAT entity.

**Comment by wbond** [comment]
I just checked the validation service - it is reporting the MC VAT ID to be from FR and the IM one to be from GB.

Theoretically I could try using a regular expression on the address to try and detect Monaco or Isle of Man, but that may affect VAT ID validation in other ways since those country codes (`IM` and `MC`) are not a valid country code for VAT IDs.

If you have more information, especially from the EU Commission about how they are supposed to be handled differently, I'd be happy to review it.
